package entities;
// Generated Sep 10, 2014 9:41:08 PM by Hibernate Tools 3.6.0



/**
 * Algorithm generated by hbm2java
 */
public class Algorithm  implements java.io.Serializable {


     private String name;
     private boolean running;

    public Algorithm() {
    }

    public Algorithm(String name, boolean running) {
       this.name = name;
       this.running = running;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public boolean isRunning() {
        return this.running;
    }
    
    public void setRunning(boolean running) {
        this.running = running;
    }




}


