package entities;
// Generated Sep 10, 2014 9:41:08 PM by Hibernate Tools 3.6.0



/**
 * Ids generated by hbm2java
 */
public class Ids  implements java.io.Serializable {


     private String name;
     private Integer idNum;

    public Ids() {
    }

	
    public Ids(String name) {
        this.name = name;
    }
    public Ids(String name, Integer idNum) {
       this.name = name;
       this.idNum = idNum;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getIdNum() {
        return this.idNum;
    }
    
    public void setIdNum(Integer idNum) {
        this.idNum = idNum;
    }




}


