package entities;
// Generated Sep 10, 2014 9:41:08 PM by Hibernate Tools 3.6.0



/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {


     private MessagesId id;
     private User user;
     private Property property;
     private String message;

    public Messages() {
    }

    public Messages(MessagesId id, User user, Property property, String message) {
       this.id = id;
       this.user = user;
       this.property = property;
       this.message = message;
    }
   
    public MessagesId getId() {
        return this.id;
    }
    
    public void setId(MessagesId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Property getProperty() {
        return this.property;
    }
    
    public void setProperty(Property property) {
        this.property = property;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }




}


