package entities;
// Generated Sep 10, 2014 9:41:08 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int userId;
     private boolean verified;
     private String username;
     private String password;
     private String email;
     private String middleName;
     private String name;
     private String surname;
     private String telephone;
     private String telephone2;
     private String fax;
     private boolean lessor;
     private boolean seller;
     private boolean lessee;
     private boolean buyer;
     private String profilePicture;
     private Date joinDate;
     private int registerIp;
     private String address1;
     private String address2;
     private String address3;
     private String city;
     private String region;
     private String postalCode;
     private String country;
     private Set<Messages> messageses;
     private Set<Property> properties;

    public User() {
    }

	
    public User(int userId, boolean verified, String username, String password, String email, String name, String surname, boolean lessor, boolean seller, boolean lessee, boolean buyer, Date joinDate, int registerIp, String address1, String city, String region, String postalCode, String country) {
        this.userId = userId;
        this.verified = verified;
        this.username = username;
        this.password = password;
        this.email = email;
        this.name = name;
        this.surname = surname;
        this.lessor = lessor;
        this.seller = seller;
        this.lessee = lessee;
        this.buyer = buyer;
        this.joinDate = joinDate;
        this.registerIp = registerIp;
        this.address1 = address1;
        this.city = city;
        this.region = region;
        this.postalCode = postalCode;
        this.country = country;
    }
    public User(int userId, boolean verified, String username, String password, String email, String middleName, String name, String surname, String telephone, String telephone2, String fax, boolean lessor, boolean seller, boolean lessee, boolean buyer, String profilePicture, Date joinDate, int registerIp, String address1, String address2, String address3, String city, String region, String postalCode, String country, Set<Messages> messageses, Set<Property> properties) {
       this.userId = userId;
       this.verified = verified;
       this.username = username;
       this.password = password;
       this.email = email;
       this.middleName = middleName;
       this.name = name;
       this.surname = surname;
       this.telephone = telephone;
       this.telephone2 = telephone2;
       this.fax = fax;
       this.lessor = lessor;
       this.seller = seller;
       this.lessee = lessee;
       this.buyer = buyer;
       this.profilePicture = profilePicture;
       this.joinDate = joinDate;
       this.registerIp = registerIp;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.city = city;
       this.region = region;
       this.postalCode = postalCode;
       this.country = country;
       this.messageses = messageses;
       this.properties = properties;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public boolean isVerified() {
        return this.verified;
    }
    
    public void setVerified(boolean verified) {
        this.verified = verified;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getTelephone2() {
        return this.telephone2;
    }
    
    public void setTelephone2(String telephone2) {
        this.telephone2 = telephone2;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public boolean isLessor() {
        return this.lessor;
    }
    
    public void setLessor(boolean lessor) {
        this.lessor = lessor;
    }
    public boolean isSeller() {
        return this.seller;
    }
    
    public void setSeller(boolean seller) {
        this.seller = seller;
    }
    public boolean isLessee() {
        return this.lessee;
    }
    
    public void setLessee(boolean lessee) {
        this.lessee = lessee;
    }
    public boolean isBuyer() {
        return this.buyer;
    }
    
    public void setBuyer(boolean buyer) {
        this.buyer = buyer;
    }
    public String getProfilePicture() {
        return this.profilePicture;
    }
    
    public void setProfilePicture(String profilePicture) {
        this.profilePicture = profilePicture;
    }
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }
    public int getRegisterIp() {
        return this.registerIp;
    }
    
    public void setRegisterIp(int registerIp) {
        this.registerIp = registerIp;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Set<Messages> getMessageses() {
        return this.messageses;
    }
    
    public void setMessageses(Set<Messages> messageses) {
        this.messageses = messageses;
    }
    public Set<Property> getProperties() {
        return this.properties;
    }
    
    public void setProperties(Set<Property> properties) {
        this.properties = properties;
    }




}


